IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'cooperation_log' AND COLUMN_NAME = 'sent_at')
  ALTER TABLE cooperation_log ADD sent_at DATETIME NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'cooperation_log' AND COLUMN_NAME = 'received_at')
  ALTER TABLE cooperation_log ADD received_at DATETIME NULL
GO
